name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install PNPM
        run: |
          npm install -g pnpm
          echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Install Dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run Tests
        run: pnpm test

      - name: Commit Message Lint
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
